source 'https://github.com/CocoaPods/Specs.git'

target 'SWPageViewController', :exclusive => true do
  pod "SWPageViewController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SWPageViewController", :path => "../"

  
end
